# Data Collection and Exploration — NVIDIA Tweets Dataset

## 1. Import Libraries

This section imports the Python libraries needed for loading, checking, and visualising the NVIDIA tweets dataset.

In [7]:
import pandas as pd
import matplotlib.pyplot as plt

## 2. Load the Dataset

The dataset used in this project is a public Kaggle dataset containing NVIDIA related tweets. 

The dataset will be used to analyse NVIDIA-related social media attention, tweet sentiment, and network relationships between hashtags, cashtags, mentions and users.

In [8]:
file_path = "../data/raw/Nvidia-Tweets.csv"

df = pd.read_csv(file_path)

df.head()

,Unnamed: 0,Datetime,Tweet Id,Text,Username
0,0,2023-02-06 10:07:17+00:00,1.622537e+18,$nvda Top analyst price target for next week ...,RyderJohnston6
1,1,2023-02-06 10:06:30+00:00,1.622537e+18,$nvda Top analyst price target for this week.🔗...,k_mebane
2,2,2023-02-06 10:06:08+00:00,1.622537e+18,$nvda Top analyst price target for next week.....,RonaldBevan2
3,3,2023-02-06 10:05:43+00:00,1.622537e+18,$NVDA Top analyst target price for next week🚀 ...,Eva077777
4,4,2023-02-06 10:03:49+00:00,1.622537e+18,$rsls rebound 🚨🚨🚀🚀🚀\n————\n\n$EDSA\n$KODK\n$DO...,MrBlackTrading

## 3. Check Dataset Size and Columns
This section checks the number of rows and columns in the dataset, it also displays the column names to understand what information is available for analysis.

In [9]:
df.shape

(100847, 5)

In [10]:
df.columns

Index(['Unnamed: 0', 'Datetime', 'Tweet Id', 'Text', 'Username'], dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100847 entries, 0 to 100846
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  100847 non-null  str
 1   Datetime    100369 non-null  str
 2   Tweet Id    100001 non-null  float64
 3   Text        100001 non-null  str
 4   Username    99633 non-null   str
dtypes: float64(1), str(4)
memory usage: 3.8 MB

## 4. Check Missing Values

Missing values are checked to identify whether important fields such as tweet text, username, tweet ID, or datetime are incomplete.

In [12]:
df.isnull().sum()

Unnamed: 0       0
Datetime       478
Tweet Id       846
Text           846
Username      1214
dtype: int64

## 5. Check Duplicate Data

In [13]:
df.duplicated().sum()

np.int64(393)

In [14]:
df["Tweet Id"].duplicated().sum()

np.int64(845)

In [15]:
df["Text"].duplicated().sum()

np.int64(9756)

## 6. Convert Datetime Column

The `Datetime` column is converted into a proper datetime format, which allows the dataset to be analysed over time and later merged with NVIDIA stock price data.

In [16]:
df["Datetime"] = pd.to_datetime(df["Datetime"], errors="coerce")

df[["Datetime"]].head()

                   Datetime
0 2023-02-06 10:07:17+00:00
1 2023-02-06 10:06:30+00:00
2 2023-02-06 10:06:08+00:00
3 2023-02-06 10:05:43+00:00
4 2023-02-06 10:03:49+00:00

## 7. Check Dataset Time Period

This section checks the start and end dates of the tweet dataset, which is important because the time period of the NVIDIA stock price dataset must cover the same date range.

In [17]:
start_date = df["Datetime"].min()
end_date = df["Datetime"].max()

start_date, end_date

(Timestamp('2022-11-21 14:30:16+0000', tz='UTC'),
 Timestamp('2023-02-06 10:07:17+0000', tz='UTC'))